<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="optimizationrule" nsURI="http://bumble.org/xtext/optimizationrule/DSL"
    nsPrefix="org.bumble.xtext.grammaroptimizer">
  <eClassifiers xsi:type="ecore:EClass" name="OptimizationRule" abstract="true">
    <eOperations name="apply"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grammar" eType="ecore:EClass ../../org.bumble.xtext.grammartransformer.grammarrule/model/GrammarRule.ecore#//Grammar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grammarRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveBraces" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludedGrammarRule" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddKeywordToAttr" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywordName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenameKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Convert1toStarToStar" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Convert1toStarToPlus" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeOptionalAttrToOrRelation" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludedGrammarRule" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveXStarAttrKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveComma" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveLine" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveRule" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Convert1ToStarTo1" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveRuleCall" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calledRuleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddKeywordAfterKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeTypeOfAttr" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddParenthesesToAttr" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveParenthesesInAttribute" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddImport" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newImport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveAttribute" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeAttrLineContent" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newLineContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenameRule" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveAttributeKeywords" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveOptionality" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeBracesToParentheses" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeBracesToSquare" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeBracesToAngle" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveOutermostBraces" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Convert1toStarTo1orStar" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveBracesExceptOutermost" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveCertainTypeFromAttr" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeRuleContent" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeCalledRule" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentCalledRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newCalledRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeCommaToOtherSymbol" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveAttrToAfterRuleKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="movedLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddStringToRuleKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addedString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddOptionalityToAttr" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveImport" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="import" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddAlternativeKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddOptionalityToKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddBracesToAttr" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeywordUpperToLowerCase" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddSquareBracketToAttr" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddOptionalityToOutermostBraces" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//MultiplicityKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddSymbolToAttr" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoredAttributes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyCommonRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyUpperBoundOne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddPrimitiveType" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaclass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddSymbolToRule" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bInside" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddKeywordToLine" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddParenthesesWithoutQuotes" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//ScopeKey"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//MultiplicityKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeKey">
    <eLiterals name="singlekeword"/>
    <eLiterals name="singleline" value="1"/>
    <eLiterals name="multilines" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddOptionalityToSymbol" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddSymbolToLine" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFront" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddSymbolWithoutQuoteToLine" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFront" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeABtoBAB" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopyAttrAToAttrB" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFront" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopyXfromStarToY" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrInX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrInY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFront" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Convert1toStarToTwo" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeAToOptionalAorA" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddTerminalRule" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddOptionalityToLine" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddBracesToLine" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddParenthesesWithoutQuoteToRule" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//MultiplicityKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddAlternativeSymbol" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeABToABorBA" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddSymbolWithoutQuoteToKeyword" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFront" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeAttributeMultiplicity" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//MultiplicityKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeBooleanAttrToSpecialPattern" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeAttributeToSingleElementOrBracedList"
      eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeReturns" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newReturns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddAlternativeValue" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeAToAorSymbol" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MultiplicityKey">
    <eLiterals name="PackageOnly"/>
    <eLiterals name="MultiplicityOptional" value="1" literal="MultiplicityOptional"/>
    <eLiterals name="MultiplicityZeroOrMore" value="2" literal="MultiplicityZeroOrMore"/>
    <eLiterals name="MultiplicityOneOrMore" value="3" literal="MultiplicityOneOrMore"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddAlternativeSubClassToAbstractClass"
      eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAlternativeSubClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddBracesToRule" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveLiteralFromEnum" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literalName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Convert0toStarTo0toStaror1toStar" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveAction" eSuperTypes="#//OptimizationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddCallToOtherRule" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameOfOtherClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callRequired" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetAstProperty" eSuperTypes="#//OptimizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multi" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
